### ISSUE TITLE
Can't make a chest

### ISSUE THREAD

**Issue by reji8627** [Silverrain2004/Aberration-Adventure-Expert#1]
While following the questbook, I quickly found out that chests require double compressed wood, planks, and crafting tables, none of which have recipes to make, in fact, the only twilight and frozen stone have recipes for all the compression levels, and only cobble, sand, dirt and gravel have recipes for 2x, and that recipe requires a factorizer.

**Comment by Silverrain2004** [comment]
Hi There @reji8627 since the first beta-phase is finished. I move on to the next Stage. That means all will change with the Pack.
